language: node_js
node_js:
- '0.12'
env:
- CMD="npm test"
- CMD="npm run test-accessibility"
script: "$CMD"
sudo: true
before_install:
- bundle install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
    - /^v\d+.\d+.\d+$/
notifications:
  email: false
  slack:
    secure: FMGitfi3qf7sN8RwtZBw5vi3gWDt2l3v0n+SzMv5XorZKUAbZQ4wBayfHPt683Z1UufyiE63tjaBrutfbNYiOV9QSQjdeS3M5jKa177UhulgbdRNEAiCp+gmzPRjfnAWdoq+43dhGbqZBXY20jFH3A6jngbJHouo5dzZhBEKApuSJQg3gV6y/6VgPfTabYY8iNG4c1LusDRQMS18KjXGiOFud0oPFHaGlKZE9N/cU8BeV6EFAKcGNkR1EgT5PGOWXArdBa1lxwlcCwmLqGK5DOX99xjcmrAGuEMSMpwiugnoUrye7c+0QW/M9KWQHDVqt+HvKO0dZ4raNJQD+2P2fCchWn/+Gxk0y3wgwqKhtR+C2zAcwPcKaMix/S3j0pxZuzkyu1xr6bK4IiPdacZj9HY5Qy4PYkUrgyDa8TA69Y4S+OrInsjnoGusr8VjoqiiQm0QqPDMRav258a7KuN7ay/akJ3scygMyky3NWEI1f6GSA+53Dj689qb3Fv80sWAFr476/1zDHZKTMI5f7dJ/R3p9RA8dwpYIJzso3gUCi35YOFyrjs3bYJPWmkv6iXzgYOPGpXCzbtiOLQeqHtyNfiO31/924k9w2ESBzpJaTlOUOr5NghMjUfa28NAyanCj3fso38iwmDmkty7kDo50L0lC+3DnhJ3dGjYMA0PJI4=
before_deploy:
- gulp release-zip
- STYLEGUIDE_ENV=staging gulp monolith
deploy:
  - provider: cloudfoundry
    api: https://api.run.pivotal.io
    username: pivotal-ui@pivotal.io
    password:
      secure: gHmcewGbR/rNN8mYej9Sr33fwkcv2eEQ/Bf3rbgsjuRcZH2o9+9j/85BxwGT41NwPfB0wX1I9RC8Gz6SHwFio1IRCR/Y1z/Jzfs1h40JwFzzN1HkFwAxdd5+61pDHOxDl7tqDoqLo5PB820QUiQ0QhZTsWsNhYoX/+u0pO/o/oACFA29wf3QTMyOYGt+ImpMRqQcNwsBHZYPHqc2twmjNLNyH3Zps+RXtnZUWY6FrfcuIbYezsfwdC2Q8pN5hRdIJ1XGLcmZYLYUYgDIAxLcY5/E6Ht6jirCgXjoy3V0Zd3iCuXZnmf9mpAvaDycKK4ZRi63gdbmzzZiPOC2/sbE2Rwk9T6v6Wci9iVJketncYd4r6ofKn0Zvm8ZzP74NuU8pOEpDXGzK+7lEtTYglO3np2gn4HRSzDI/ANirtPzW/EgD3QRkmMu7XcnvUYEusSRjYCGe3P270a2D2t/fDlYV/96Dft/7F9HNhQJVqzlUWqitO7La+kNRrGI9dCSoKUxESbtobTzrb5HG93C0YCegMnsyfJ8yRMq/8Ya9FEQEoqkZRGS6zQPwmOimQl+AuinKC3WxNPUxpfn2A1tjYOouJK+HUumNzsRLvCxQo3bMhyKD5Rx44SVQfungsWA35Zd2hEZ75YJAJ2nJqOnFSf3b71S4OR965je31m+vDMGzXo=
    organization: pivotal
    space: pivotal-ui-staging
    on:
      repo: pivotal-cf/pivotal-ui
      branch: master
  - provider: releases
    api_key:
      secure: FEY0UlBt+Rix+8LiEgNXBQUk2Jv2zpKjDCnWjPCVzRhgngDmLmxqmi0NoWqLXQ7LNqXdjVKqqYbhndOL5bJxTPyFG5kqPutVYM79iAXUSFQ3To6U57N4Bv7JeD6u97hWEw9c4VfwyysdPjop1a9ppRik6fuiPd6PBPRpPHeoFTe9azJ009KhFi5O4HGHHjWNRuZluZxoDMrHi5NBYdhxtzxEiG9aIvGgwrO6us+sdhd2CwqTV+mRxi2hmnxkK3myPSuQZWzk0M2CgXE90WwqzgcW9dp4nOKYiFYLcdwE6e9VKJMntNMv9Fy/4yyb7Q48IVoVNu5xD/jsAjydFTnowQhk7qtNjFMlMhJaVnnoflCZ9uF0Q0mXpy80G5QfqP07JRvKz49DSqiG2x1ZM+6hCnNnRg74bis1aKw0TBh2ClV5K6CYHX+b2iXVz2Hkdutlxm0mWRr7mA7GQIQXUaTW3EHXnUSOYFVBvDZSZ0zGnPX2dkQYev2j3nqAsCPl6MvmkesUusIR15GbxMtfJksa3Zrtz/68lML4bvshqHvzeUpser70FifWkA5R4Rpo/PO8b0ddRR7/K7mNovOI60mgwBKKFgEBzBIKBl/1LLrUNOFZdefglgQOHRNi5SGyOzwV2zCs4Yfw6XHRUmgyMKzVdC0VL9c+WOtc5cy7DTRGauk=
    file: pui.zip
    on:
      repo: pivotal-cf/pivotal-ui
      tags: true
after_deploy:
  - gulp release-add-release-notes
