language: node_js
node_js:
  - '0.10'
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - bundle install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email: false
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: labs-pivotal-ui@pivotal.io
  password:
    secure: BqKn0fYZL4b1JNTlt2a1APx8BQsSqwIAXfOyK198OnGyywizoXjWl9Fnu4QlEGpqLDhNX0X0v1CCvTU+zNkWWRnmLdpSK5BDRtXjvm7OPtaxHBesi7nfKEGWoAdRXXTMSC/q8mIc4z5USSA7DYu41kSgNO+Cw2Vz6XvsqAMhujo=
  organization: pivotal
  space: pivotal-ui
  on:
    repo: pivotal-cf/pivotal-ui
    branch: master
